name: Update README with Latest Projects

on:
  schedule:
    - cron: "0 * * * *"   # Updates every hour
  workflow_dispatch:       # Allows manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Latest Repos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: PROJECTS
          commit_message: "âš¡ auto update latest projects"
          feed_list: "https://rsshub.app/github/user/repos/Rashini0926"
